config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'items#index'

      resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :url, presence: true
  validates :user_id, presence: true

  before_create :set_target_price

  belongs_to :user

  def self.scrape_prices
    Item.find_each do |item|
      item.scrape_price
    end
  end

  def scrape_price
    current_price = find_price
    if current_price <  target_price
      ItemMailer.notify_price_below_target(self, current_price).deliver
    end
  end

  private

  def set_target_price
    return if target_price
    self.target_price = find_price
  end

  def find_price
    doc = Nokogiri::HTML(open(url))
    return unless price = doc.css("span#priceblock_ourprice").first.try(:text)
    price.gsub("$", "").to_f
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      flash[:notice] = "Item succesfully saved"
      redirect_to :action => "show", :id => @item.id
    else
      flash[:error] = @item.errors.full_messages
      render :new
    end
  end

  def show
    @item = Item.find_by_id(params[:id])
  end

  def edit
    @item = Item.find_by_id(params[:id])
  end

  def update
    @item = Item.find_by_id(params[:id])
    @item.attributes = item_params

    if @item.save
      flash[:notice] = "Item succesfully saved"
      redirect_to :action => "show", :id => @item.id
    else
      flash[:error] = @item.errors.full_messages
      render :new
    end
  end

  private

  def item_params
    params.require(:item).permit(:id, :target_price, :url, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= f.label :url %>
<%= f.text_field :url %>

<%= f.label :target_price %>
<%= f.text_field :target_price %>

<%= f.hidden_field :user_id, :value => current_user.id %>

<%= f.submit "Create item" %>

app/views/items/edit.html.erb
<h1>Edit item</h1>

<%= form_for @item do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
<% end %>

app/views/items/index.html.erb
<h1>Items</h1>
<table>
  <th>ID</th>
  <th>URL</th>
  <th>Target Price</th>
  <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= item.url %></td>
      <td><%= item.target_price %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Add new item", new_item_path %>

app/views/items/new.html.erb
<h1>Create new item</h1>

<%= form_for @item do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
<% end %>

app/views/items/show.html.erb
<h1>Item Details</h1>

<table>
  <th>ID</th>
  <th>URL</th>
  <th>Target Price</th>
  <tr>
    <td><%= @item.id %></td>
    <td><%= @item.url %></td>
    <td><%= @item.target_price %></td>
  </tr>
</table>

<%= link_to "Edit Item", edit_item_path(@item) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmazonScraper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        BRAND
      </a>
    </div>
  </div>
  <div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        </li>
      <% else %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>
          </li>
      <% end %>
    </ul>
  </div>
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>